### PR TITLE
Removed deprecated iteractionResponseTypes

### PR DESCRIPTION
**Pull request by Andols0**

### CODE REVIEW

**Comment by Andols0** [comment]
Discord have removed some interactionsResponseTypes in PR https://github.com/discord/discord-api-docs/pull/2615

**Comment by GitSparTV** [comment]
Thanks for the PR, I will merge this but I plan to rewrite the library.

**Comment by Andols0** [comment]
No worries, was testing the lib out when discord announced the change.
Didn't know if you were active in maintaining at the moment :)

**Comment by GitSparTV** [comment]
Hi I forgot to merge this, but I finish rewrite for new changes

**Comment by GitSparTV** [comment]
If I missed something create an issue

**Pull request closed without merging**
